# Generated by Django 4.2.29 on 2026-03-13 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('file_size', models.IntegerField(verbose_name='文件大小')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('category', models.CharField(choices=[('avatar', '头像'), ('document', '文档'), ('image', '图片'), ('other', '其他')], max_length=50, verbose_name='文件分类')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
            },
        ),
    ]
