# Generated by Django 4.2.29 on 2026-03-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('config_name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('ai', 'AI配置'), ('vector', '向量库配置')], max_length=50, verbose_name='配置类型')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
