# Generated by Django 4.2.29 on 2026-03-13 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='知识库名称')),
                ('description', models.TextField(blank=True, verbose_name='知识库描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('file_size', models.IntegerField(verbose_name='文件大小')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], max_length=20, verbose_name='处理状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgeinfo', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识库附件',
                'verbose_name_plural': '知识库附件',
            },
        ),
    ]
