# Generated by Django 6.0.3 on 2026-03-13 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='工作流名称')),
                ('description', models.TextField(blank=True, verbose_name='工作流描述')),
                ('definition', models.JSONField(verbose_name='工作流定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流管理',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='执行状态')),
                ('input_data', models.JSONField(blank=True, null=True, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, null=True, verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n8n.workflow', verbose_name='关联工作流')),
            ],
            options={
                'verbose_name': '执行历史',
                'verbose_name_plural': '执行历史管理',
            },
        ),
    ]
